repos:

- repo: https://github.com/python-poetry/poetry
  rev: 1.7.0
  hooks:
    - id: poetry-check
      name: "validating poetry state \U0001F50F"

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
